; generated by Slic3r 0.9.10b on 2014-02-25 at 03:09:19

; layer_height = 0.2
; perimeters = 2
; top_solid_layers = 3
; bottom_solid_layers = 3
; fill_density = 0.3
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; nozzle_diameter = 0.35
; filament_diameter = 1.75
; extrusion_multiplier = 1.1
; perimeters extrusion width = 0.52mm
; infill extrusion width = 0.52mm
; solid infill extrusion width = 0.52mm
; top infill extrusion width = 0.52mm
; first layer extrusion width = 0.40mm

G21 ; set units to millimeters
M107 ; disable fan
M190 S60 ; wait for bed temperature to be reached
M104 S185 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S185 ; wait for temperature to be reached
G90 ; use absolute coordinates
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
G1 F1800.000 E-1.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.000 F7800.000 ; move to next layer (0)
G1 X94.407 Y91.110 ; move to first skirt point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X95.437 Y90.160 F540.000 E1.04989 ; skirt
G1 X96.627 Y89.430 E1.09960 ; skirt
G1 X97.927 Y88.920 E1.14932 ; skirt
G1 X99.307 Y88.660 E1.19932 ; skirt
G1 X100.697 Y88.670 E1.24881 ; skirt
G1 X102.077 Y88.920 E1.29874 ; skirt
G1 X103.377 Y89.430 E1.34846 ; skirt
G1 X104.567 Y90.170 E1.39836 ; skirt
G1 X105.597 Y91.120 E1.44825 ; skirt
G1 X106.437 Y92.240 E1.49809 ; skirt
G1 X108.767 Y96.010 E1.65589 ; skirt
G1 X109.387 Y97.250 E1.70525 ; skirt
G1 X109.777 Y98.590 E1.75494 ; skirt
G1 X109.907 Y99.980 E1.80465 ; skirt
G1 X109.777 Y101.370 E1.85435 ; skirt
G1 X109.397 Y102.710 E1.90395 ; skirt
G1 X108.777 Y103.960 E1.95362 ; skirt
G1 X106.427 Y107.770 E2.11301 ; skirt
G1 X105.587 Y108.880 E2.16257 ; skirt
G1 X104.557 Y109.830 E2.21246 ; skirt
G1 X103.367 Y110.560 E2.26217 ; skirt
G1 X102.067 Y111.070 E2.31189 ; skirt
G1 X100.697 Y111.320 E2.36147 ; skirt
G1 X99.297 Y111.320 E2.41132 ; skirt
G1 X97.927 Y111.070 E2.46090 ; skirt
G1 X96.617 Y110.560 E2.51095 ; skirt
G1 X95.437 Y109.820 E2.56055 ; skirt
G1 X94.407 Y108.880 E2.61019 ; skirt
G1 X93.567 Y107.770 E2.65976 ; skirt
G1 X91.217 Y103.960 E2.81914 ; skirt
G1 X90.597 Y102.710 E2.86882 ; skirt
G1 X90.217 Y101.360 E2.91875 ; skirt
G1 X90.087 Y99.970 E2.96846 ; skirt
G1 X90.227 Y98.580 E3.01820 ; skirt
G1 X90.607 Y97.230 E3.06813 ; skirt
G1 X91.237 Y95.980 E3.11797 ; skirt
G1 X93.567 Y92.230 E3.27517 ; skirt
G1 X94.372 Y91.157 E3.32293 ; skirt
G1 X94.687 Y91.370 F7800.000 ; move to first skirt point
G1 X95.667 Y90.480 F540.000 E3.37007 ; skirt
G1 X96.797 Y89.780 E3.41739 ; skirt
G1 X98.037 Y89.300 E3.46474 ; skirt
G1 X99.337 Y89.050 E3.51187 ; skirt
G1 X100.667 Y89.050 E3.55923 ; skirt
G1 X101.967 Y89.300 E3.60636 ; skirt
G1 X103.207 Y89.780 E3.65370 ; skirt
G1 X104.327 Y90.480 E3.70073 ; skirt
G1 X105.307 Y91.380 E3.74810 ; skirt
G1 X106.107 Y92.440 E3.79538 ; skirt
G1 X108.437 Y96.210 E3.95318 ; skirt
G1 X109.027 Y97.390 E4.00015 ; skirt
G1 X109.387 Y98.660 E4.04715 ; skirt
G1 X109.517 Y99.980 E4.09438 ; skirt
G1 X109.397 Y101.300 E4.14157 ; skirt
G1 X109.037 Y102.570 E4.18857 ; skirt
G1 X108.447 Y103.750 E4.23554 ; skirt
G1 X106.097 Y107.560 E4.39493 ; skirt
G1 X105.297 Y108.620 E4.44221 ; skirt
G1 X104.327 Y109.520 E4.48932 ; skirt
G1 X103.197 Y110.210 E4.53646 ; skirt
G1 X101.957 Y110.690 E4.58381 ; skirt
G1 X100.657 Y110.940 E4.63094 ; skirt
G1 X99.337 Y110.940 E4.67794 ; skirt
G1 X98.027 Y110.690 E4.72542 ; skirt
G1 X96.797 Y110.210 E4.77243 ; skirt
G1 X95.667 Y109.510 E4.81976 ; skirt
G1 X94.687 Y108.620 E4.86689 ; skirt
G1 X93.897 Y107.560 E4.91396 ; skirt
G1 X91.547 Y103.760 E5.07304 ; skirt
G1 X90.957 Y102.570 E5.12033 ; skirt
G1 X90.597 Y101.290 E5.16768 ; skirt
G1 X90.477 Y99.970 E5.21487 ; skirt
G1 X90.607 Y98.650 E5.26209 ; skirt
G1 X90.977 Y97.380 E5.30919 ; skirt
G1 X91.567 Y96.190 E5.35648 ; skirt
G1 X93.897 Y92.430 E5.51398 ; skirt
G1 X94.652 Y91.417 E5.55897 ; skirt
G1 X95.067 Y91.540 F7800.000 ; move to first skirt point
G1 X96.107 Y90.640 F540.000 E5.60794 ; skirt
G1 X97.317 Y89.970 E5.65718 ; skirt
G1 X98.627 Y89.550 E5.70616 ; skirt
G1 X99.997 Y89.410 E5.75520 ; skirt
G1 X101.377 Y89.550 E5.80458 ; skirt
G1 X102.687 Y89.970 E5.85356 ; skirt
G1 X103.897 Y90.640 E5.90281 ; skirt
G1 X104.937 Y91.550 E5.95201 ; skirt
G1 X105.777 Y92.640 E6.00101 ; skirt
G1 X108.107 Y96.420 E6.15911 ; skirt
G1 X108.747 Y97.770 E6.21230 ; skirt
G1 X109.087 Y99.230 E6.26568 ; skirt
G1 X109.087 Y100.730 E6.31908 ; skirt
G1 X108.757 Y102.190 E6.37238 ; skirt
G1 X108.117 Y103.550 E6.42589 ; skirt
G1 X105.767 Y107.360 E6.58528 ; skirt
G1 X104.927 Y108.450 E6.63427 ; skirt
G1 X103.887 Y109.350 E6.68324 ; skirt
G1 X102.677 Y110.020 E6.73249 ; skirt
G1 X101.367 Y110.440 E6.78147 ; skirt
G1 X99.997 Y110.580 E6.83050 ; skirt
G1 X98.627 Y110.440 E6.87953 ; skirt
G1 X97.307 Y110.020 E6.92885 ; skirt
G1 X96.107 Y109.350 E6.97779 ; skirt
G1 X95.067 Y108.450 E7.02676 ; skirt
G1 X94.227 Y107.360 E7.07575 ; skirt
G1 X91.877 Y103.550 E7.23513 ; skirt
G1 X91.237 Y102.190 E7.28865 ; skirt
G1 X90.907 Y100.730 E7.34195 ; skirt
G1 X90.917 Y99.220 E7.39571 ; skirt
G1 X91.247 Y97.750 E7.44935 ; skirt
G1 X91.897 Y96.400 E7.50270 ; skirt
G1 X94.227 Y92.630 E7.66050 ; skirt
G1 X95.031 Y91.586 E7.70741 ; skirt
G1 X95.347 Y91.810 F7800.000 ; move to first skirt point
G1 X96.337 Y90.960 F540.000 E7.75387 ; skirt
G1 X97.467 Y90.320 E7.80011 ; skirt
G1 X98.707 Y89.930 E7.84639 ; skirt
G1 X99.997 Y89.800 E7.89255 ; skirt
G1 X101.297 Y89.930 E7.93907 ; skirt
G1 X102.537 Y90.330 E7.98546 ; skirt
G1 X103.667 Y90.960 E8.03152 ; skirt
G1 X104.647 Y91.810 E8.07771 ; skirt
G1 X105.437 Y92.850 E8.12421 ; skirt
G1 X107.777 Y96.620 E8.28220 ; skirt
G1 X108.387 Y97.900 E8.33268 ; skirt
G1 X108.697 Y99.270 E8.38269 ; skirt
G1 X108.697 Y100.690 E8.43325 ; skirt
G1 X108.387 Y102.070 E8.48361 ; skirt
G1 X107.787 Y103.340 E8.53362 ; skirt
G1 X105.437 Y107.150 E8.69301 ; skirt
G1 X104.647 Y108.180 E8.73922 ; skirt
G1 X103.657 Y109.030 E8.78568 ; skirt
G1 X102.527 Y109.670 E8.83192 ; skirt
G1 X101.287 Y110.060 E8.87820 ; skirt
G1 X99.997 Y110.190 E8.92436 ; skirt
G1 X98.707 Y110.060 E8.97053 ; skirt
G1 X97.467 Y109.670 E9.01681 ; skirt
G1 X96.327 Y109.030 E9.06336 ; skirt
G1 X95.347 Y108.180 E9.10955 ; skirt
G1 X94.557 Y107.150 E9.15576 ; skirt
G1 X92.207 Y103.350 E9.31484 ; skirt
G1 X91.607 Y102.070 E9.36518 ; skirt
G1 X91.297 Y100.680 E9.41588 ; skirt
G1 X91.297 Y99.260 E9.46644 ; skirt
G1 X91.617 Y97.880 E9.51688 ; skirt
G1 X92.227 Y96.600 E9.56736 ; skirt
G1 X94.557 Y92.840 E9.72486 ; skirt
G1 X95.311 Y91.856 E9.76900 ; skirt
G1 F1800.000 E8.76900 ; retract
G92 E0 ; reset extrusion distance
G1 X99.779 Y99.779 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.974 Y99.699 F540.000 E1.00750 ; perimeter
G1 X100.090 Y99.714 E1.01168 ; perimeter
G1 X100.226 Y99.793 E1.01728 ; perimeter
G1 X100.312 Y100.000 E1.02527 ; perimeter
G1 X100.221 Y100.221 E1.03378 ; perimeter
G1 X100.000 Y100.312 E1.04229 ; perimeter
G1 X99.779 Y100.221 E1.05080 ; perimeter
G1 X99.688 Y100.000 E1.05931 ; perimeter
G1 X99.757 Y99.833 E1.06574 ; perimeter
G1 X99.974 Y99.860 F7800.000 ; move inwards before travel
G1 F1800.000 E0.06574 ; retract
G92 E0 ; reset extrusion distance
G1 X100.000 Y102.284 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X100.513 Y102.601 F540.000 E1.02148 ; perimeter
G1 X100.000 Y103.432 E1.05625 ; perimeter
G1 X99.487 Y102.601 E1.09102 ; perimeter
G1 X99.950 Y102.315 E1.11041 ; perimeter
G1 X100.130 Y102.651 F7800.000 ; move inwards before travel
G1 X100.000 Y101.906 ; move to first perimeter point
G1 X98.945 Y100.198 F540.000 E1.18190 ; perimeter
G1 X98.262 Y100.619 E1.21046 ; perimeter
G1 X97.880 Y100.000 E1.23636 ; perimeter
G1 X98.262 Y99.381 E1.26227 ; perimeter
G1 X98.945 Y99.802 E1.29083 ; perimeter
G1 X100.000 Y98.094 E1.36232 ; perimeter
G1 X101.055 Y99.802 E1.43380 ; perimeter
G1 X101.738 Y99.381 E1.46236 ; perimeter
G1 X102.120 Y100.000 E1.48827 ; perimeter
G1 X101.738 Y100.619 E1.51417 ; perimeter
G1 X101.055 Y100.198 E1.54273 ; perimeter
G1 X100.031 Y101.856 E1.61214 ; perimeter
G1 X99.929 Y101.523 F7800.000 ; move inwards before travel
G1 F1800.000 E0.61214 ; retract
G92 E0 ; reset extrusion distance
G1 X100.000 Y97.716 F7800.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.487 Y97.399 F540.000 E1.02148 ; perimeter
G1 X100.000 Y96.568 E1.05625 ; perimeter
G1 X100.513 Y97.399 E1.09102 ; perimeter
G1 X100.050 Y97.685 E1.11041 ; perimeter
G1 X99.870 Y97.349 F7800.000 ; move inwards before travel
G1 X100.589 Y100.192 ; move to first fill point
G1 X100.547 Y100.150 F360.000 E1.11151 ; fill
G1 X100.789 Y100.106 E1.11605 ; fill
G1 X100.558 Y99.875 E1.12210 ; fill
G1 X100.670 Y99.702 E1.12591 ; fill
G1 X100.639 Y99.670 E1.12673 ; fill
G1 X99.471 Y100.217 F7800.000 ; move to first fill point
G1 X99.187 Y99.933 F360.000 E1.13412 ; fill
G1 X99.296 Y99.756 F7800.000 ; move to first fill point
G1 X99.434 Y99.895 F360.000 E1.13771 ; fill
M106 S650 ; enable fan
G1 F1800.000 E0.13771 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.200 F7800.000 ; move to next layer (1)
G1 X99.638 Y100.000 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.744 Y99.744 F600.000 E1.01219 ; perimeter
G1 X99.967 Y99.652 E1.02283 ; perimeter
G1 X100.079 Y99.666 E1.02776 ; perimeter
G1 X100.258 Y99.749 E1.03647 ; perimeter
G1 X100.362 Y100.000 E1.04840 ; perimeter
G1 X100.256 Y100.256 E1.06059 ; perimeter
G1 X100.000 Y100.362 E1.07278 ; perimeter
G1 X99.744 Y100.256 E1.08497 ; perimeter
G1 X99.666 Y100.067 E1.09398 ; perimeter
G1 X99.894 Y99.894 F7800.000 ; move inwards before travel
G1 X99.075 Y99.262 ; move to first perimeter point
G1 X99.181 Y99.006 F600.000 E1.10617 ; perimeter
G1 X99.078 Y98.757 E1.11803 ; perimeter
G1 X98.846 Y98.647 E1.12931 ; perimeter
G1 X99.068 Y98.288 E1.14785 ; perimeter
G1 X99.401 Y98.426 E1.16371 ; perimeter
G1 X99.657 Y98.320 E1.17589 ; perimeter
G1 X99.763 Y98.064 E1.18808 ; perimeter
G1 X99.660 Y97.815 E1.19994 ; perimeter
G1 X99.428 Y97.704 E1.21122 ; perimeter
G1 X100.000 Y96.779 E1.25907 ; perimeter
G1 X100.576 Y97.712 E1.30731 ; perimeter
G1 X100.343 Y97.808 E1.31840 ; perimeter
G1 X100.237 Y98.064 E1.33059 ; perimeter
G1 X100.343 Y98.320 E1.34278 ; perimeter
G1 X100.599 Y98.426 E1.35497 ; perimeter
G1 X100.932 Y98.288 E1.37082 ; perimeter
G1 X101.158 Y98.654 E1.38974 ; perimeter
G1 X100.925 Y98.750 E1.40083 ; perimeter
G1 X100.819 Y99.006 E1.41302 ; perimeter
G1 X100.925 Y99.262 E1.42521 ; perimeter
G1 X101.181 Y99.368 E1.43740 ; perimeter
G1 X101.514 Y99.230 E1.45325 ; perimeter
G1 X101.990 Y100.000 E1.49306 ; perimeter
G1 X101.509 Y100.778 E1.53328 ; perimeter
G1 X101.264 Y100.660 E1.54523 ; perimeter
G1 X101.149 Y100.645 E1.55035 ; perimeter
G1 X100.925 Y100.738 E1.56100 ; perimeter
G1 X100.819 Y100.994 E1.57318 ; perimeter
G1 X100.925 Y101.250 E1.58537 ; perimeter
G1 X101.158 Y101.346 E1.59646 ; perimeter
G1 X100.927 Y101.720 E1.61581 ; perimeter
G1 X100.682 Y101.603 E1.62776 ; perimeter
G1 X100.567 Y101.588 E1.63288 ; perimeter
G1 X100.343 Y101.680 E1.64352 ; perimeter
G1 X100.237 Y101.936 E1.65571 ; perimeter
G1 X100.343 Y102.192 E1.66790 ; perimeter
G1 X100.576 Y102.288 E1.67899 ; perimeter
G1 X100.000 Y103.221 E1.72723 ; perimeter
G1 X99.424 Y102.288 E1.77546 ; perimeter
G1 X99.657 Y102.192 E1.78655 ; perimeter
G1 X99.763 Y101.936 E1.79874 ; perimeter
G1 X99.660 Y101.687 E1.81060 ; perimeter
G1 X99.484 Y101.603 E1.81918 ; perimeter
G1 X99.368 Y101.588 E1.82430 ; perimeter
G1 X99.068 Y101.712 E1.83861 ; perimeter
G1 X98.842 Y101.346 E1.85753 ; perimeter
G1 X99.075 Y101.250 E1.86862 ; perimeter
G1 X99.181 Y100.994 E1.88081 ; perimeter
G1 X99.078 Y100.745 E1.89267 ; perimeter
G1 X98.902 Y100.660 E1.90125 ; perimeter
G1 X98.786 Y100.645 E1.90637 ; perimeter
G1 X98.486 Y100.770 E1.92068 ; perimeter
G1 X98.010 Y100.000 E1.96048 ; perimeter
G1 X98.486 Y99.230 E2.00028 ; perimeter
G1 X98.819 Y99.368 E2.01614 ; perimeter
G1 X99.008 Y99.290 E2.02515 ; perimeter
G1 X99.349 Y99.298 F7800.000 ; move inwards before travel
G1 F1800.000 E1.02515 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.400 F7800.000 ; move to next layer (2)
G1 X99.744 Y99.744 ; move to first perimeter point
G1 F1800.000 E1.00000 ; compensate retraction
G1 X99.967 Y99.652 F600.000 E1.01064 ; perimeter
G1 X100.122 Y99.672 E1.01748 ; perimeter
G1 X100.313 Y99.819 E1.02812 ; perimeter
G1 X100.347 Y100.076 E1.03952 ; perimeter
G1 X100.239 Y100.263 E1.04902 ; perimeter
G1 X100.000 Y100.362 E1.06041 ; perimeter
G1 X99.744 Y100.256 E1.07260 ; perimeter
G1 X99.638 Y100.000 E1.08479 ; perimeter
G1 X99.716 Y99.811 E1.09381 ; perimeter
G1 X99.967 Y99.837 F7800.000 ; move inwards before travel
G1 X99.058 Y99.269 ; move to first perimeter point
G1 X99.166 Y99.082 F600.000 E1.10331 ; perimeter
G1 X99.132 Y98.825 E1.11470 ; perimeter
G1 X98.915 Y98.659 E1.12674 ; perimeter
G1 X99.129 Y98.313 E1.14461 ; perimeter
G1 X99.401 Y98.426 E1.15757 ; perimeter
G1 X99.657 Y98.320 E1.16976 ; perimeter
G1 X99.756 Y98.081 E1.18116 ; perimeter
G1 X99.700 Y97.872 E1.19066 ; perimeter
G1 X99.497 Y97.717 E1.20190 ; perimeter
G1 X100.000 Y96.903 E1.24400 ; perimeter
G1 X100.515 Y97.737 E1.28714 ; perimeter
G1 X100.343 Y97.808 E1.29533 ; perimeter
G1 X100.237 Y98.064 E1.30752 ; perimeter
G1 X100.343 Y98.320 E1.31971 ; perimeter
G1 X100.599 Y98.426 E1.33190 ; perimeter
G1 X100.871 Y98.313 E1.34486 ; perimeter
G1 X101.097 Y98.679 E1.36378 ; perimeter
G1 X100.925 Y98.750 E1.37197 ; perimeter
G1 X100.819 Y99.006 E1.38416 ; perimeter
G1 X100.925 Y99.262 E1.39635 ; perimeter
G1 X101.181 Y99.368 E1.40854 ; perimeter
G1 X101.453 Y99.256 E1.42150 ; perimeter
G1 X101.913 Y100.000 E1.46000 ; perimeter
G1 X101.438 Y100.769 E1.49978 ; perimeter
G1 X101.303 Y100.665 E1.50727 ; perimeter
G1 X101.149 Y100.645 E1.51411 ; perimeter
G1 X100.925 Y100.738 E1.52475 ; perimeter
G1 X100.819 Y100.994 E1.53694 ; perimeter
G1 X100.925 Y101.250 E1.54913 ; perimeter
G1 X101.097 Y101.321 E1.55732 ; perimeter
G1 X100.856 Y101.712 E1.57753 ; perimeter
G1 X100.721 Y101.608 E1.58503 ; perimeter
G1 X100.567 Y101.588 E1.59186 ; perimeter
G1 X100.343 Y101.680 E1.60251 ; perimeter
G1 X100.237 Y101.936 E1.61469 ; perimeter
G1 X100.343 Y102.192 E1.62688 ; perimeter
G1 X100.515 Y102.263 E1.63507 ; perimeter
G1 X100.000 Y103.097 E1.67822 ; perimeter
G1 X99.485 Y102.263 E1.72136 ; perimeter
G1 X99.657 Y102.192 E1.72956 ; perimeter
G1 X99.763 Y101.936 E1.74174 ; perimeter
G1 X99.664 Y101.697 E1.75314 ; perimeter
G1 X99.506 Y101.606 E1.76115 ; perimeter
G1 X99.368 Y101.588 E1.76726 ; perimeter
G1 X99.129 Y101.687 E1.77867 ; perimeter
G1 X98.903 Y101.321 E1.79760 ; perimeter
G1 X99.075 Y101.250 E1.80579 ; perimeter
G1 X99.174 Y101.010 E1.81719 ; perimeter
G1 X99.118 Y100.802 E1.82668 ; perimeter
G1 X98.940 Y100.665 E1.83653 ; perimeter
G1 X98.786 Y100.645 E1.84337 ; perimeter
G1 X98.547 Y100.744 E1.85478 ; perimeter
G1 X98.087 Y100.000 E1.89328 ; perimeter
G1 X98.547 Y99.256 E1.93178 ; perimeter
G1 X98.819 Y99.368 E1.94474 ; perimeter
G1 X98.991 Y99.297 E1.95296 ; perimeter
G1 X99.269 Y99.316 F7800.000 ; move inwards before travel
G1 F1800.000 E0.95296 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used = 11.6mm (0.0cm3)

; avoid_crossing_perimeters = 
; bed_size = 200,200
; bed_temperature = 60
; bottom_solid_layers = 3
; bridge_acceleration = 0
; bridge_fan_speed = 255
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 1
; duplicate = 1
; duplicate_distance = 6
; duplicate_grid = 1,1
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors
; external_perimeter_speed = 70%
; external_perimeters_first = 
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1.1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_diameter = 1.75
; fill_angle = 45
; fill_density = 0.3
; fill_pattern = honeycomb
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 200%
; first_layer_height = 0.2
; first_layer_speed = 30%
; first_layer_temperature = 185
; g0 = 0
; gap_fill_speed = 20
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_speed = 60
; layer_gcode = 
; layer_height = 0.2
; max_fan_speed = 255
; min_fan_speed = 150
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.35
; only_retract_when_crossing_perimeters = 1
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 30
; perimeters = 2
; post_process = 
; print_center = 100,100
; raft_layers = 0
; randomize_start = 1
; resolution = .01
; retract_before_travel = 2
; retract_layer_change = 1
; retract_length = 1
; retract_length_toolchange = 10
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 30
; rotate = 0
; scale = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 4
; slowdown_below_layer_time = 30
; small_perimeter_speed = 30
; solid_fill_pattern = rectilinear
; solid_infill_below_area = 70
; solid_infill_every_layers = 3
; solid_infill_extrusion_width = 0
; solid_infill_speed = 60
; spiral_vase = 0
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle
; support_material = 
; support_material_angle = 0
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_layers = 0
; support_material_interface_spacing = 0
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 0
; temperature = 185
; threads = 6
; toolchange_gcode = 
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 50
; top_solid_layers = 3
; travel_speed = 130
; use_relative_e_distances = 0
; vibration_limit = 0
; wipe = 0
; z_offset = -.2
